kind: pipeline
name: test

steps:
- name: flake8
  image: alpine/flake8:3.7.8
  commands:
  - flake8

- name: pytest
  image: vmck/vagrant-vmck:0.3.0
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER"
  - cp examples/.env ./
  - echo "CODECOV_TOKEN=$CODECOV_TOKEN" >> .env
  - trap "vagrant destroy -f"  EXIT
  - vagrant up
  - vagrant ssh -- /vagrant/ci/test-pytest.sh
  - vagrant ssh -- /vagrant/ci/codecov.sh
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token

---
kind: pipeline
name: publish

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: vmck/acs-interface
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: vmck/acs-interface
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
