# -*- mode: ruby -*-
# vi: set ft=ruby :

 Vagrant.configure("2") do |config|
  config.vm.box = "base"

   if Vagrant.has_plugin?('vagrant-env')
    config.env.enable
  end

   config.nfs.functional = false

   config.vm.provision 'shell', inline: "cd /vagrant; unzip submission.zip"

   config.vm.provider :vmck do |vmck|
    !CONFIGUARATION!
  end
end
