# Generated by Django 2.2.4 on 2019-08-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=64)),
                ('assignment_id', models.CharField(default='none', max_length=64)),
                ('url', models.CharField(default='none', max_length=256)),
                ('token', models.CharField(default='none', max_length=128)),
                ('score', models.IntegerField(default=-1)),
            ],
        ),
    ]
