# Generated by Django 2.2.5 on 2019-09-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('max_score', models.IntegerField(default=100)),
                ('repo_url', models.CharField(blank=True, max_length=256)),
                ('repo_branch', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(default='none', max_length=4096)),
                ('state', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done')], default='new', max_length=32)),
                ('score', models.IntegerField(null=True)),
                ('review_score', models.IntegerField(null=True)),
                ('archive_size', models.IntegerField(null=True)),
                ('vmck_job_id', models.IntegerField(null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.Assignment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.Course'),
        ),
    ]
