# Generated by Django 2.2.4 on 2019-08-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='submission',
            name='message',
            field=models.CharField(default='none', max_length=4096),
        ),
    ]
