# Generated by Django 2.2.4 on 2019-09-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20190831_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='token',
        ),
    ]
