# Generated by Django 2.2.5 on 2019-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_submission_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
