# Generated by Django 2.2.4 on 2019-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_remove_submission_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='url',
            new_name='_url',
        ),
        migrations.AddField(
            model_name='submission',
            name='review_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
