# Generated by Django 2.2.6 on 2019-10-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20191006_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
