# Generated by Django 2.2.6 on 2019-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20191006_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.CharField(default='none', max_length=8192),
        ),
    ]
