# Generated by Django 2.2.6 on 2019-10-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20191006_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='output',
            new_name='stdout',
        ),
        migrations.AddField(
            model_name='submission',
            name='stderr',
            field=models.CharField(default='none', max_length=4096),
        ),
    ]
