# Generated by Django 2.2.6 on 2019-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20191006_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output_err',
            field=models.CharField(default='none', max_length=4096),
        ),
    ]
