# Generated by Django 2.2.4 on 2019-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20190906_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='archive_size',
            field=models.IntegerField(null=True),
        ),
    ]
