# Generated by Django 2.2.6 on 2019-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20191014_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.CharField(default='none', max_length=32768),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
