# Generated by Django 2.2.6 on 2019-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20191014_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='output',
            field=models.CharField(default='none', max_length=32768),
        ),
    ]
