# Generated by Django 2.2.6 on 2019-10-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20191016_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='output',
            new_name='stdout',
        ),
        migrations.AddField(
            model_name='submission',
            name='stderr',
            field=models.CharField(default='none', max_length=32768),
        ),
    ]
