# Generated by Django 2.2.4 on 2019-09-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20190908_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='_state',
            new_name='state',
        ),
    ]
