# Generated by Django 2.2.6 on 2019-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20191016_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
