# Generated by Django 2.2.6 on 2019-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20191016_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='penalty',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
