# Generated by Django 2.2.5 on 2019-09-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20190908_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='none', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='_url',
        ),
    ]
