# Generated by Django 2.2.6 on 2019-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20191025_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='penalty',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
