# Generated by Django 2.2.5 on 2019-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20190912_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_id',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='assignment',
            name='branch',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
