# Generated by Django 2.2.5 on 2019-09-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0010_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='message',
            new_name='output',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='vmck_id',
            new_name='vmck_job_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='username',
        ),
        migrations.AddField(
            model_name='assignment',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='repo_branch',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='assignment',
            name='repo_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.Assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.Course'),
        ),
    ]
