# Generated by Django 2.2.6 on 2019-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20191104_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
