# Generated by Django 2.2.6 on 2019-11-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20191113_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='stderr',
            field=models.TextField(blank=True, default='', max_length=32768),
        ),
        migrations.AlterField(
            model_name='submission',
            name='stdout',
            field=models.TextField(blank=True, default='', max_length=32768),
        ),
        migrations.AlterField(
            model_name='submission',
            name='review_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
