# Generated by Django 2.2.6 on 2019-12-09 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20191121_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline_hard',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 9, 14, 13, 70759, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline_soft',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 9, 14, 22, 650662, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
