# Generated by Django 3.0.2 on 2020-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.CharField(choices=[('c', 'c'), ('py', 'python'), ('java', 'java')], default='c', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='language',
            field=models.CharField(choices=[('c', 'c'), ('py', 'python'), ('java', 'java')], default='c', max_length=32),
        ),
    ]
