# Generated by Django 3.0.2 on 2020-01-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='min_time_between_uploads',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='min_time_between_uploads',
            field=models.IntegerField(default=60),
        ),
    ]
