# Generated by Django 3.0.2 on 2020-01-13 08:51

from django.db import migrations, models


def set_repo_path(apps, schema_editor):
    Assignment = apps.get_model('interface', 'Assignment')
    for assignment in Assignment.objects.all():
        assignment.repo_path = assignment.repo_branch
        assignment.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_min_time_between_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='repo_path',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='repo_path',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.RunPython(set_repo_path, do_nothing),
    ]
