# Generated by Django 3.0.5 on 2020-05-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_assignment_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
