# Generated by Django 3.0.3 on 2020-04-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_assignment_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue')], default='new', max_length=32),
        ),
    ]
