# Generated by Django 3.0.3 on 2020-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_assignment_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='code',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue')], default='new', max_length=32),
        ),
    ]
