# Generated by Django 3.0.5 on 2020-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_auto_20200509_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalassignment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='code',
        ),
    ]
