# Generated by Django 3.0.6 on 2020-06-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_auto_20200522_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubmission',
            old_name='vmck_job_id',
            new_name='evaluator_job_id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='vmck_job_id',
            new_name='evaluator_job_id',
        ),
    ]
