# Generated by Django 3.0.5 on 2020-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_auto_20200509_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalassignment',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
