# Generated by Django 3.0.6 on 2020-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_auto_20200619_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hidden_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='hidden_score',
            field=models.BooleanField(default=True),
        ),
    ]
