# Generated by Django 3.1.1 on 2020-09-26 11:32

from django.db import migrations, models
import interface.models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_auto_20200709_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image_path',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='penalty_info',
            field=models.JSONField(default=interface.models.Assignment.get_default_penalty_info),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vm_options',
            field=models.JSONField(default=interface.models.Assignment.get_default_vm_info),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='image_path',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='penalty_info',
            field=models.JSONField(default=interface.models.Assignment.get_default_penalty_info),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='vm_options',
            field=models.JSONField(default=interface.models.Assignment.get_default_vm_info),
        ),
    ]
