# Generated by Django 3.1.2 on 2020-10-24 16:49

from django.db import migrations, models
import interface.models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_auto_20200709_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image_path',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AddField(
            model_name='assignment',
            name='penalty_info',
            field=models.JSONField(default=interface.models.get_default_penalty_info),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vm_options',
            field=models.JSONField(default=interface.models.get_default_vm_info),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='image_path',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='penalty_info',
            field=models.JSONField(default=interface.models.get_default_penalty_info),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='vm_options',
            field=models.JSONField(default=interface.models.get_default_vm_info),
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue'), ('error', 'Error')], default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue'), ('error', 'Error')], default='queued', max_length=32),
        ),
    ]
