# Generated by Django 3.0.6 on 2020-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubmission',
            name='preliminary_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='preliminary_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
