# Generated by Django 3.1.2 on 2021-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_auto_20201024_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalassignment',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
