# Generated by Django 3.1.2 on 2020-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_auto_20201022_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue'), ('error', 'Error')], default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('done', 'Done'), ('queued', 'Queue'), ('error', 'Error')], default='queued', max_length=32),
        ),
    ]
