name: Lint
on: [push, pull_request]
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
 
            - name: Flake8
              uses: tonybajan/flake8-check-action@v1.0.0
              with:
                repotoken: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Black
              uses: jpetrucciani/black-check@20.8b1
