name: Lint
on: [push, pull_request]
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run Flake8
              uses: tonybajan/flake8-check-action@v1.0.0
              with:
                repotoken: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Black
              uses: jpetrucciani/black-check@20.8b1

            - name: Run ShellCheck
              uses: ludeeus/action-shellcheck@0.5.0
              with:
                scandir: './ci'
