name: Lint

on: [ push, pull_request ]

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.7.10

            - name: Provision System
              shell: bash
              run: ./ci/provision-system.sh

            - name: Run Flake8
              shell: bash
              run: flakehell lint

            - name: Run Black
              uses: jpetrucciani/black-check@20.8b1

            - name: Run ShellCheck
              uses: ludeeus/action-shellcheck@0.5.0
              with:
                severity: warning
