name: Lint

on: [ push, pull_request ]

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: Install Python dependencies
              shell: bash
              run: pip install flakehell flake8 flake8-bugbear flake8-django \
                  flake8-eradicate flake8-comprehensions flake8-return \
                  flake8-simplify pep8-naming flake8-use-fstring \
                  flake8-logging-format flake8-pytest-style flake8-pytest \
                  flake8-fixme flake8-commas flake8-builtins flake8-debugger \
                  flake8-mutable

            - name: Run Flake8
              shell: bash
              run: |
                flakehell --version
                flakehell plugins
                flakehell lint

            - name: Run Black
              uses: jpetrucciani/black-check@20.8b1

            - name: Run ShellCheck
              uses: ludeeus/action-shellcheck@0.5.0
              with:
                severity: warning
