name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    Publish:
        runs-on: ubuntu-latest
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Get Current Branch Name
            uses: nelonoel/branch-name@v1

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: ${{ github.repository }}:${{ env.BRANCH_NAME }}
